[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = ".vitepress/dist"
  command = "npx pnpm i --no-frozen-lockfile --store=node_modules/.pnpm-store && npm run build"

[[redirects]]
  from = "/blog/*"
  to = "/:splat"
  status = 200